/**
 * b34-execution-gates — one-shot credential transport failures.
 * Never include credential bytes in error messages.
 */

export const BLOCKED_B34_CREDENTIAL_TRANSPORT_UNAVAILABLE =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_UNAVAILABLE" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_UNAUTHORIZED =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_UNAUTHORIZED" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_CONSUMED =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_CONSUMED" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_AMBIGUOUS =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_AMBIGUOUS" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_FRAME_INVALID =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_FRAME_INVALID" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_TIMEOUT =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_TIMEOUT" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_SHELL_FORBIDDEN =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_SHELL_FORBIDDEN" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_FALLBACK_FORBIDDEN =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_FALLBACK_FORBIDDEN" as const;
export const BLOCKED_B34_CREDENTIAL_TRANSPORT_SOURCE_UNAUTHORIZED =
  "BLOCKED_B34_CREDENTIAL_TRANSPORT_SOURCE_UNAUTHORIZED" as const;

export function assertB34CredentialTransportUnavailable(detail: string): never {
  throw new Error(`${BLOCKED_B34_CREDENTIAL_TRANSPORT_UNAVAILABLE}: ${detail}`);
}

export function assertB34NoTransportFallback(): never {
  throw new Error(
    `${BLOCKED_B34_CREDENTIAL_TRANSPORT_FALLBACK_FORBIDDEN}: pipe failure must not fall back to env, argv, stdin prompt, clipboard, or file`,
  );
}
