/**
 * b361-execution-gates — JIT one-shot signing mandate blockers.
 *
 * Human mandate authorizes deterministic derivation of at most one exact
 * signing authorization. It never opens credentials, never signs, never pays.
 */

export const BLOCKED_B361_HUMAN_SIGNING_MANDATE_MISSING =
  "BLOCKED_B361_HUMAN_SIGNING_MANDATE_MISSING" as const;
export const BLOCKED_B361_HUMAN_SIGNING_MANDATE_INVALID =
  "BLOCKED_B361_HUMAN_SIGNING_MANDATE_INVALID" as const;
export const BLOCKED_B361_HUMAN_SIGNING_MANDATE_EXPIRED =
  "BLOCKED_B361_HUMAN_SIGNING_MANDATE_EXPIRED" as const;
export const BLOCKED_B361_HUMAN_SIGNING_MANDATE_ALREADY_CONSUMED =
  "BLOCKED_B361_HUMAN_SIGNING_MANDATE_ALREADY_CONSUMED" as const;
export const BLOCKED_B361_FRESH_REQUIREMENTS_OUTSIDE_HUMAN_MANDATE =
  "BLOCKED_B361_FRESH_REQUIREMENTS_OUTSIDE_HUMAN_MANDATE" as const;
export const BLOCKED_B361_DERIVED_AUTHORITY_NOT_SUBSET =
  "BLOCKED_B361_DERIVED_AUTHORITY_NOT_SUBSET" as const;
export const BLOCKED_B361_MANDATE_LIFECYCLE_INVALID =
  "BLOCKED_B361_MANDATE_LIFECYCLE_INVALID" as const;
export const BLOCKED_B361_MANDATE_CONSUMED_AMBIGUOUS_REAUTHORIZE =
  "MANDATE_CONSUMED_AMBIGUOUS_REAUTHORIZE" as const;
export const GUARD_HUMAN_SIGNING_MANDATE_CANNOT_BYPASS_EXACT_SIGNING_AUTHORIZATION =
  "GUARD_HUMAN_SIGNING_MANDATE_CANNOT_BYPASS_EXACT_SIGNING_AUTHORIZATION" as const;
