/**
 * b363-execution-gates — conditional credential+signing mandate blockers/guards.
 *
 * Human conditional mandate may authorize at most one credential acquisition and
 * one signer invocation after exact JIT derivation. It never crosses provider,
 * TTY, or signer boundaries directly. Signing never implies payment send.
 */

export const BLOCKED_B363_CONDITIONAL_MANDATE_MISSING =
  "BLOCKED_B363_CONDITIONAL_MANDATE_MISSING" as const;
export const BLOCKED_B363_CONDITIONAL_MANDATE_INVALID =
  "BLOCKED_B363_CONDITIONAL_MANDATE_INVALID" as const;
export const BLOCKED_B363_CONDITIONAL_MANDATE_EXPIRED =
  "BLOCKED_B363_CONDITIONAL_MANDATE_EXPIRED" as const;
export const BLOCKED_B363_CONDITIONAL_MANDATE_ALREADY_CONSUMED =
  "BLOCKED_B363_CONDITIONAL_MANDATE_ALREADY_CONSUMED" as const;
export const BLOCKED_B363_FRESH_REQUIREMENTS_OUTSIDE_CONDITIONAL_MANDATE =
  "BLOCKED_B363_FRESH_REQUIREMENTS_OUTSIDE_CONDITIONAL_MANDATE" as const;
export const BLOCKED_B363_DERIVED_AUTHORITY_NOT_SUBSET =
  "BLOCKED_B363_DERIVED_AUTHORITY_NOT_SUBSET" as const;
export const BLOCKED_B363_CONDITIONAL_MANDATE_LIFECYCLE_INVALID =
  "BLOCKED_B363_CONDITIONAL_MANDATE_LIFECYCLE_INVALID" as const;
export const BLOCKED_B363_CONDITIONAL_MANDATE_AMBIGUOUS_REAUTHORIZE =
  "MANDATE_CONSUMED_AMBIGUOUS_REAUTHORIZE" as const;

export const GUARD_HUMAN_CONDITIONAL_MANDATE_NOT_DIRECTLY_CREDENTIAL_CAPABLE =
  "GUARD_HUMAN_CONDITIONAL_MANDATE_NOT_DIRECTLY_CREDENTIAL_CAPABLE" as const;
export const GUARD_HUMAN_CONDITIONAL_MANDATE_NOT_DIRECTLY_SIGNABLE =
  "GUARD_HUMAN_CONDITIONAL_MANDATE_NOT_DIRECTLY_SIGNABLE" as const;
export const GUARD_DERIVED_CREDENTIAL_AUTHORITY_SUBSET =
  "GUARD_DERIVED_CREDENTIAL_AUTHORITY_SUBSET" as const;
export const GUARD_SIGNING_DOES_NOT_AUTHORIZE_SEND =
  "GUARD_SIGNING_DOES_NOT_AUTHORIZE_SEND" as const;
