/**
 * b37-execution-gates — conditional one-shot payment send mandate blockers/guards.
 *
 * Human send mandate may authorize at most one payment-bearing request after
 * exact JIT derivation of PaymentSendAuthorization. It never reaches the
 * network directly. Signing authorization never implies send.
 */

export const BLOCKED_B37_SEND_MANDATE_MISSING =
  "BLOCKED_B37_SEND_MANDATE_MISSING" as const;
export const BLOCKED_B37_SEND_MANDATE_INVALID =
  "BLOCKED_B37_SEND_MANDATE_INVALID" as const;
export const BLOCKED_B37_SEND_MANDATE_EXPIRED =
  "BLOCKED_B37_SEND_MANDATE_EXPIRED" as const;
export const BLOCKED_B37_SEND_MANDATE_ALREADY_CONSUMED =
  "BLOCKED_B37_SEND_MANDATE_ALREADY_CONSUMED" as const;
export const BLOCKED_B37_DERIVED_SEND_AUTHORITY_NOT_SUBSET =
  "BLOCKED_B37_DERIVED_SEND_AUTHORITY_NOT_SUBSET" as const;
export const BLOCKED_B37_POST_SIGN_AUDIT_FAILED_NO_PAYMENT =
  "BLOCKED_B37_POST_SIGN_AUDIT_FAILED_NO_PAYMENT" as const;
export const BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_MISSING =
  "BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_MISSING" as const;
export const BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_INVALID =
  "BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_INVALID" as const;
export const BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_EXPIRED =
  "BLOCKED_B37_PAYMENT_SEND_AUTHORIZATION_EXPIRED" as const;
export const BLOCKED_B37_SEND_LIFECYCLE_INVALID =
  "BLOCKED_B37_SEND_LIFECYCLE_INVALID" as const;
export const BLOCKED_B37_SECOND_PAYMENT_BEARING_REQUEST =
  "BLOCKED_B37_SECOND_PAYMENT_BEARING_REQUEST" as const;
export const BLOCKED_B37_RESEND_AFTER_AMBIGUOUS_SEND =
  "BLOCKED_B37_RESEND_AFTER_AMBIGUOUS_SEND" as const;
export const BLOCKED_B37_SEND_TEMPORAL_WINDOW_CLOSED =
  "BLOCKED_B37_SEND_TEMPORAL_WINDOW_CLOSED" as const;

export const AMBIGUOUS_SEND_TERMINAL_RECONCILE =
  "AMBIGUOUS_SEND_TERMINAL_RECONCILE" as const;

export const POST_SIGN_JIT_AUDIT_PASS = "POST_SIGN_JIT_AUDIT_PASS" as const;

export const GUARD_SIGNING_AUTHORIZATION_CANNOT_AUTHORIZE_SEND =
  "GUARD_SIGNING_AUTHORIZATION_CANNOT_AUTHORIZE_SEND" as const;
export const GUARD_HUMAN_SEND_MANDATE_CANNOT_DIRECTLY_REACH_NETWORK =
  "GUARD_HUMAN_SEND_MANDATE_CANNOT_DIRECTLY_REACH_NETWORK" as const;
export const GUARD_PAYMENT_SEND_REQUIRES_EXACT_DERIVED_AUTHORIZATION =
  "GUARD_PAYMENT_SEND_REQUIRES_EXACT_DERIVED_AUTHORIZATION" as const;
export const GUARD_PAYMENT_SEND_ONE_SHOT_NO_RETRY =
  "GUARD_PAYMENT_SEND_ONE_SHOT_NO_RETRY" as const;
export const GUARD_NO_RESEND_AFTER_AMBIGUOUS_SEND =
  "GUARD_NO_RESEND_AFTER_AMBIGUOUS_SEND" as const;
export const GUARD_SEND_MANDATE_CANNOT_AUTHORIZE_SIGNING =
  "GUARD_SEND_MANDATE_CANNOT_AUTHORIZE_SIGNING" as const;
export const GUARD_SEND_MANDATE_CANNOT_AUTHORIZE_CREDENTIAL_ACCESS =
  "GUARD_SEND_MANDATE_CANNOT_AUTHORIZE_CREDENTIAL_ACCESS" as const;
