/**
 * b371-execution-gates — productive one-shot payment send bridge blockers/guards.
 *
 * Authorization input: exact PaymentSendAuthorization.
 * Credential: persisted signed buyer authorization (never a private key).
 */

export const BLOCKED_B371_PAYMENT_SEND_BINDING_MISMATCH =
  "BLOCKED_B371_PAYMENT_SEND_BINDING_MISMATCH" as const;
export const BLOCKED_B371_PAYMENT_SEND_AUTHORIZATION_EXPIRED =
  "BLOCKED_B371_PAYMENT_SEND_AUTHORIZATION_EXPIRED" as const;
export const BLOCKED_B371_PAYMENT_SEND_AUTHORIZATION_INVALID =
  "BLOCKED_B371_PAYMENT_SEND_AUTHORIZATION_INVALID" as const;
export const BLOCKED_B371_PAYMENT_HEADER_CONSTRUCTION_FAILED =
  "BLOCKED_B371_PAYMENT_HEADER_CONSTRUCTION_FAILED" as const;
export const BLOCKED_B371_SEND_COMMIT_REQUIRED =
  "BLOCKED_B371_SEND_COMMIT_REQUIRED" as const;
export const BLOCKED_B371_REDIRECT_NOT_ALLOWED =
  "BLOCKED_B371_REDIRECT_NOT_ALLOWED" as const;
export const BLOCKED_B371_TRANSPORT_FAILED =
  "BLOCKED_B371_TRANSPORT_FAILED" as const;

export const GUARD_PRODUCTIVE_SEND_BRIDGE_CANNOT_SIGN =
  "GUARD_PRODUCTIVE_SEND_BRIDGE_CANNOT_SIGN" as const;
export const GUARD_NO_RESEND_AFTER_SEND_COMMIT =
  "GUARD_NO_RESEND_AFTER_SEND_COMMIT" as const;
export const GUARD_NO_PAYMENT_HEADER_SECRET_LEAKAGE =
  "GUARD_NO_PAYMENT_HEADER_SECRET_LEAKAGE" as const;
export const GUARD_B37_OPERATIONAL_PAYMENT_CANNOT_USE_KEY_HELD_LIVE_EXECUTOR =
  "GUARD_B37_OPERATIONAL_PAYMENT_CANNOT_USE_KEY_HELD_LIVE_EXECUTOR" as const;
export const GUARD_SEND_IMPLEMENTATION_AVAILABLE_NOT_AUTHORIZATION =
  "GUARD_SEND_IMPLEMENTATION_AVAILABLE_NOT_AUTHORIZATION" as const;

export const B371_PRODUCTIVE_SEND_BRIDGE_ID =
  "trustforge_productive_one_shot_payment_sender.v1" as const;
