/**
 * b4-execution-gates — B.4 unified mainnet operationalization guards.
 */

export const BLOCKED_B4_SIGNER_SETUP_ADDRESS_MISMATCH =
  "BLOCKED_B4_SIGNER_SETUP_ADDRESS_MISMATCH" as const;
export const BLOCKED_B4_PROTECTED_SIGNER_UNAVAILABLE =
  "BLOCKED_B4_PROTECTED_SIGNER_UNAVAILABLE" as const;
export const BLOCKED_B4_SIGNER_SETUP_CANCELLED =
  "BLOCKED_B4_SIGNER_SETUP_CANCELLED" as const;
export const BLOCKED_B4_SIGNER_SETUP_INVALID =
  "BLOCKED_B4_SIGNER_SETUP_INVALID" as const;
export const BLOCKED_B4_VAULT_CORRUPT =
  "BLOCKED_B4_VAULT_CORRUPT" as const;
export const BLOCKED_B4_HUMAN_REJECTED =
  "BLOCKED_B4_HUMAN_REJECTED" as const;
export const BLOCKED_B4_HUMAN_DECISION_ABORTED =
  "BLOCKED_B4_HUMAN_DECISION_ABORTED" as const;
export const BLOCKED_B4_HUMAN_DECISION_UI_FAILED =
  "BLOCKED_B4_HUMAN_DECISION_UI_FAILED" as const;
export const BLOCKED_B4_RUNNER_STATE_INVALID =
  "BLOCKED_B4_RUNNER_STATE_INVALID" as const;
export const BLOCKED_B4_RUNNER_TERMINAL =
  "BLOCKED_B4_RUNNER_TERMINAL" as const;
export const BLOCKED_B4_APPROVAL_REQUIRED =
  "BLOCKED_B4_APPROVAL_REQUIRED" as const;

export const GUARD_NO_NORMAL_PAYMENT_PRIVATE_KEY_PROMPT =
  "GUARD_NO_NORMAL_PAYMENT_PRIVATE_KEY_PROMPT" as const;
export const GUARD_NO_PLAINTEXT_BUYER_KEY_PERSISTENCE =
  "GUARD_NO_PLAINTEXT_BUYER_KEY_PERSISTENCE" as const;
export const GUARD_NO_PROTECTED_SIGNER_FALLBACK_TO_ENV =
  "GUARD_NO_PROTECTED_SIGNER_FALLBACK_TO_ENV" as const;
export const GUARD_NO_PROTECTED_SIGNER_FALLBACK_TO_FILE_PLAINTEXT =
  "GUARD_NO_PROTECTED_SIGNER_FALLBACK_TO_FILE_PLAINTEXT" as const;
export const GUARD_PAYMENT_REQUIRES_EXACT_APPROVAL_ARTIFACTS =
  "GUARD_PAYMENT_REQUIRES_EXACT_APPROVAL_ARTIFACTS" as const;
export const GUARD_HUMAN_REJECT_CANNOT_REACH_SIGNER =
  "GUARD_HUMAN_REJECT_CANNOT_REACH_SIGNER" as const;
export const GUARD_THIN_RUNNER_CANNOT_BYPASS_PSA =
  "GUARD_THIN_RUNNER_CANNOT_BYPASS_PSA" as const;
export const GUARD_THIN_RUNNER_CANNOT_RETRY_SEND =
  "GUARD_THIN_RUNNER_CANNOT_RETRY_SEND" as const;
export const GUARD_ONLY_EXPLICIT_BUTTON_PRODUCES_REJECT =
  "GUARD_ONLY_EXPLICIT_BUTTON_PRODUCES_REJECT" as const;
export const GUARD_WINDOW_CLOSE_IS_ABORT_NOT_REJECT =
  "GUARD_WINDOW_CLOSE_IS_ABORT_NOT_REJECT" as const;
export const GUARD_NO_APPROVAL_DIALOG_AUTO_TIMEOUT =
  "GUARD_NO_APPROVAL_DIALOG_AUTO_TIMEOUT" as const;
export const GUARD_APPROVAL_SCRIPT_MUST_BE_PS51_SAFE =
  "GUARD_APPROVAL_SCRIPT_MUST_BE_PS51_SAFE" as const;
export const WINDOWS_PS51_APPROVAL_SCRIPT_ENCODING_SAFE =
  "WINDOWS_PS51_APPROVAL_SCRIPT_ENCODING_SAFE" as const;
/** Automated suites must never spawn the visible production Approve/Reject UI. */
export const GUARD_AUTOMATED_TESTS_CANNOT_INVOKE_PRODUCTION_APPROVAL_UI =
  "GUARD_AUTOMATED_TESTS_CANNOT_INVOKE_PRODUCTION_APPROVAL_UI" as const;
export const BLOCKED_B4_PRODUCTION_APPROVAL_UI_WITHOUT_OPERATIONAL_CONTEXT =
  "BLOCKED_B4_PRODUCTION_APPROVAL_UI_WITHOUT_OPERATIONAL_CONTEXT" as const;

export const B4_PROTECTED_SIGNER_PROVIDER_ID =
  "windows-dpapi-local-signer" as const;
export const B4_PROTECTED_SIGNER_CREDENTIAL_KIND =
  "windows_dpapi_protected_private_key" as const;
export const B4_PROTECTED_VAULT_SECRET_ENTRY =
  "WINDOWS_DPAPI_VAULT_ONE_SHOT" as const;
export const B4_APPROVE_REJECT_DECISION_PROVIDER_ID =
  "windows-approve-reject-dialog" as const;
export const B4_MANUAL_APPROVE_REJECT_POLICY =
  "manual-approve-reject" as const;
