/**
 * b52-execution-gates — B.5.2 OttoAI approval-binding + diversity payment guards.
 */

export const GUARD_OPERATIONAL_UI_RENDERS_AUTHORITATIVE_PAYMENT_INTENT =
  "GUARD_OPERATIONAL_UI_RENDERS_AUTHORITATIVE_PAYMENT_INTENT" as const;

export const GUARD_HUMAN_DECISION_BINDS_PAYMENT_INTENT_HASH =
  "GUARD_HUMAN_DECISION_BINDS_PAYMENT_INTENT_HASH" as const;

export const GUARD_METHOD_BINDING_CANDIDATE_AUTHORIZATION_REQUEST =
  "GUARD_METHOD_BINDING_CANDIDATE_AUTHORIZATION_REQUEST" as const;

export const GUARD_JIT_AUTHORITY_SUBSET_OF_PAYMENT_APPROVAL_INTENT =
  "GUARD_JIT_AUTHORITY_SUBSET_OF_PAYMENT_APPROVAL_INTENT" as const;

export const BLOCKED_B52_FRESH_TERMS_DIFFER_FROM_HUMAN_APPROVAL_REAUTHORIZE =
  "BLOCKED_B52_FRESH_TERMS_DIFFER_FROM_HUMAN_APPROVAL_REAUTHORIZE" as const;

export const BLOCKED_B52_HUMAN_DECISION_UI_FAILED_NO_PAYMENT =
  "BLOCKED_B52_HUMAN_DECISION_UI_FAILED_NO_PAYMENT" as const;

export const BLOCKED_B52_APPROVAL_BINDING_NOT_READY =
  "BLOCKED_B52_APPROVAL_BINDING_NOT_READY" as const;

export const B52_APPROVAL_BINDING_READY =
  "B52_APPROVAL_BINDING_READY" as const;

export const CANDIDATE_AUTHORIZATION_REQUEST_TRIPLE_BINDING =
  "CANDIDATE_AUTHORIZATION_REQUEST_TRIPLE_BINDING" as const;

export const HUMAN_REJECTED_NO_PAYMENT = "HUMAN_REJECTED_NO_PAYMENT" as const;
export const HUMAN_DECISION_ABORTED_NO_PAYMENT =
  "HUMAN_DECISION_ABORTED_NO_PAYMENT" as const;

export const B52_OTTOAI_DIVERSITY_PAYMENT_CONFIRMED =
  "B52_OTTOAI_DIVERSITY_PAYMENT_CONFIRMED" as const;
export const B52_OTTOAI_PAYMENT_CONFIRMED_AFTER_RECONCILIATION =
  "B52_OTTOAI_PAYMENT_CONFIRMED_AFTER_RECONCILIATION" as const;
export const B52_OTTOAI_PAYMENT_ACCEPTED_RECONCILIATION_REQUIRED =
  "B52_OTTOAI_PAYMENT_ACCEPTED_RECONCILIATION_REQUIRED" as const;
export const B52_OTTOAI_SEND_AMBIGUOUS_TERMINAL_RECONCILE =
  "B52_OTTOAI_SEND_AMBIGUOUS_TERMINAL_RECONCILE" as const;
export const B52_OTTOAI_APPROVAL_BINDING_NOT_READY_NO_PAYMENT =
  "B52_OTTOAI_APPROVAL_BINDING_NOT_READY_NO_PAYMENT" as const;
