/**
 * b6-execution-gates — B.6 agentic payment decision layer has zero execution authority.
 */

export const GUARD_B6_CANNOT_SIGN = "GUARD_B6_CANNOT_SIGN" as const;
export const GUARD_B6_CANNOT_ACCESS_CREDENTIALS =
  "GUARD_B6_CANNOT_ACCESS_CREDENTIALS" as const;
export const GUARD_B6_CANNOT_CREATE_PAYMENT_HEADER =
  "GUARD_B6_CANNOT_CREATE_PAYMENT_HEADER" as const;
export const GUARD_B6_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION =
  "GUARD_B6_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION" as const;
export const GUARD_B6_CANNOT_CALL_PRODUCTIVE_PAYMENT_TRANSPORT =
  "GUARD_B6_CANNOT_CALL_PRODUCTIVE_PAYMENT_TRANSPORT" as const;
export const GUARD_B6_BUY_IS_NOT_PAYMENT_AUTHORIZATION =
  "GUARD_B6_BUY_IS_NOT_PAYMENT_AUTHORIZATION" as const;

export const GUARD_SELECTION_DECISION_BINDS_CANDIDATE_SET =
  "GUARD_SELECTION_DECISION_BINDS_CANDIDATE_SET" as const;
export const GUARD_PAYMENT_APPROVAL_INTENT_BINDS_SELECTION_DECISION =
  "GUARD_PAYMENT_APPROVAL_INTENT_BINDS_SELECTION_DECISION" as const;

export const BLOCKED_B6_VISIBLE_HUMAN_UI_REGRESSION_NO_PAYMENT =
  "BLOCKED_B6_VISIBLE_HUMAN_UI_REGRESSION_NO_PAYMENT" as const;
export const BLOCKED_B6_SELECTION_DECISION_TAMPER =
  "BLOCKED_B6_SELECTION_DECISION_TAMPER" as const;
export const BLOCKED_B6_SELECTION_STALE =
  "BLOCKED_B6_SELECTION_STALE" as const;
export const BLOCKED_B6_SELECTION_SET_DRIFT =
  "BLOCKED_B6_SELECTION_SET_DRIFT" as const;

export const B6_AGENTIC_PAYMENT_DECISION_LAYER_READY_NO_PAYMENT =
  "B6_AGENTIC_PAYMENT_DECISION_LAYER_READY_NO_PAYMENT" as const;

export function assertB6HasNoExecutionAuthority(): void {
  void GUARD_B6_CANNOT_SIGN;
  void GUARD_B6_CANNOT_ACCESS_CREDENTIALS;
  void GUARD_B6_CANNOT_CREATE_PAYMENT_HEADER;
  void GUARD_B6_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION;
  void GUARD_B6_CANNOT_CALL_PRODUCTIVE_PAYMENT_TRANSPORT;
  void GUARD_B6_BUY_IS_NOT_PAYMENT_AUTHORIZATION;
}
