/**
 * b61-execution-gates — B.6.1 objective-bound decisions have zero execution authority.
 */

export const GUARD_OBJECTIVE_MATCH_PRECEDES_ECONOMIC_RANKING =
  "GUARD_OBJECTIVE_MATCH_PRECEDES_ECONOMIC_RANKING" as const;
export const GUARD_SELECTION_DECISION_BINDS_OBJECTIVE =
  "GUARD_SELECTION_DECISION_BINDS_OBJECTIVE" as const;
export const GUARD_PAYMENT_APPROVAL_INTENT_BINDS_OBJECTIVE =
  "GUARD_PAYMENT_APPROVAL_INTENT_BINDS_OBJECTIVE" as const;

export const OBJECTIVE_REQUIRED = "OBJECTIVE_REQUIRED" as const;
export const OBJECTIVE_SELECTION_BINDING_MISMATCH =
  "OBJECTIVE_SELECTION_BINDING_MISMATCH" as const;
export const OBJECTIVE_BUDGET_EXCEEDED = "OBJECTIVE_BUDGET_EXCEEDED" as const;
export const NO_RELEVANT_CANDIDATE = "NO_RELEVANT_CANDIDATE" as const;
export const NEED_MORE_DISCOVERY = "NEED_MORE_DISCOVERY" as const;
export const OUT_OF_SCOPE_OBJECTIVE = "OUT_OF_SCOPE_OBJECTIVE" as const;

export const BLOCKED_B61_VISIBLE_UI_REGRESSION_NO_PAYMENT =
  "BLOCKED_B61_VISIBLE_UI_REGRESSION_NO_PAYMENT" as const;
export const BLOCKED_B61_OBJECTIVE_TAMPER =
  "BLOCKED_B61_OBJECTIVE_TAMPER" as const;

export const B61_OBJECTIVE_BOUND_PAYMENT_DECISION_READY_NO_PAYMENT =
  "B61_OBJECTIVE_BOUND_PAYMENT_DECISION_READY_NO_PAYMENT" as const;

export const GUARD_B61_CANNOT_SIGN = "GUARD_B61_CANNOT_SIGN" as const;
export const GUARD_B61_CANNOT_ACCESS_DPAPI =
  "GUARD_B61_CANNOT_ACCESS_DPAPI" as const;
export const GUARD_B61_CANNOT_CREATE_PAYMENT_HEADER =
  "GUARD_B61_CANNOT_CREATE_PAYMENT_HEADER" as const;
export const GUARD_B61_CANNOT_SEND = "GUARD_B61_CANNOT_SEND" as const;

export function assertB61HasNoExecutionAuthority(): void {
  void GUARD_B61_CANNOT_SIGN;
  void GUARD_B61_CANNOT_ACCESS_DPAPI;
  void GUARD_B61_CANNOT_CREATE_PAYMENT_HEADER;
  void GUARD_B61_CANNOT_SEND;
  void GUARD_OBJECTIVE_MATCH_PRECEDES_ECONOMIC_RANKING;
}
