/**
 * b62-execution-gates — B.6.2 payment-need provenance has zero execution authority.
 */

export const GUARD_OBJECTIVE_REQUIRES_ESTABLISHED_PAYMENT_NEED =
  "GUARD_OBJECTIVE_REQUIRES_ESTABLISHED_PAYMENT_NEED" as const;
export const GUARD_OBJECTIVE_DOES_NOT_BROADEN_PAYMENT_NEED =
  "GUARD_OBJECTIVE_DOES_NOT_BROADEN_PAYMENT_NEED" as const;
export const GUARD_OBJECTIVE_DERIVATION_IS_CANDIDATE_INDEPENDENT =
  "GUARD_OBJECTIVE_DERIVATION_IS_CANDIDATE_INDEPENDENT" as const;
export const GUARD_SATISFIED_NEED_CANNOT_TRIGGER_NEW_BUY =
  "GUARD_SATISFIED_NEED_CANNOT_TRIGGER_NEW_BUY" as const;
export const GUARD_NEED_OBJECTIVE_SELECTION_INTENT_CHAIN =
  "GUARD_NEED_OBJECTIVE_SELECTION_INTENT_CHAIN" as const;

export const NO_ESTABLISHED_PAYMENT_NEED = "NO_ESTABLISHED_PAYMENT_NEED" as const;
export const UNSUPPORTED_NEED = "UNSUPPORTED_NEED" as const;
export const OBJECTIVE_NEED_MISMATCH = "OBJECTIVE_NEED_MISMATCH" as const;
export const OBJECTIVE_BROADENS_NEED_BUDGET =
  "OBJECTIVE_BROADENS_NEED_BUDGET" as const;
export const OBJECTIVE_BROADENS_NEED_NETWORK =
  "OBJECTIVE_BROADENS_NEED_NETWORK" as const;
export const OBJECTIVE_BROADENS_NEED_CAPABILITY =
  "OBJECTIVE_BROADENS_NEED_CAPABILITY" as const;
export const DUPLICATE_ACTIVE_NEED = "DUPLICATE_ACTIVE_NEED" as const;
export const NEED_LIFECYCLE_NOT_ACTIVE = "NEED_LIFECYCLE_NOT_ACTIVE" as const;

export const BLOCKED_B62_VISIBLE_UI_REGRESSION_NO_PAYMENT =
  "BLOCKED_B62_VISIBLE_UI_REGRESSION_NO_PAYMENT" as const;
export const BLOCKED_B62_NEED_TAMPER = "BLOCKED_B62_NEED_TAMPER" as const;

export const B62_PAYMENT_NEED_OBJECTIVE_PROVENANCE_READY_NO_PAYMENT =
  "B62_PAYMENT_NEED_OBJECTIVE_PROVENANCE_READY_NO_PAYMENT" as const;

export const GUARD_B62_CANNOT_SIGN = "GUARD_B62_CANNOT_SIGN" as const;
export const GUARD_B62_CANNOT_ACCESS_CREDENTIALS =
  "GUARD_B62_CANNOT_ACCESS_CREDENTIALS" as const;
export const GUARD_B62_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION =
  "GUARD_B62_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION" as const;
export const GUARD_B62_CANNOT_CREATE_PAYMENT_HEADER =
  "GUARD_B62_CANNOT_CREATE_PAYMENT_HEADER" as const;
export const GUARD_B62_CANNOT_CALL_PRODUCTIVE_TRANSPORT =
  "GUARD_B62_CANNOT_CALL_PRODUCTIVE_TRANSPORT" as const;

export function assertB62HasNoExecutionAuthority(): void {
  void GUARD_B62_CANNOT_SIGN;
  void GUARD_B62_CANNOT_ACCESS_CREDENTIALS;
  void GUARD_B62_CANNOT_CREATE_PAYMENT_SEND_AUTHORIZATION;
  void GUARD_B62_CANNOT_CREATE_PAYMENT_HEADER;
  void GUARD_B62_CANNOT_CALL_PRODUCTIVE_TRANSPORT;
  void GUARD_OBJECTIVE_REQUIRES_ESTABLISHED_PAYMENT_NEED;
  void GUARD_OBJECTIVE_DOES_NOT_BROADEN_PAYMENT_NEED;
  void GUARD_OBJECTIVE_DERIVATION_IS_CANDIDATE_INDEPENDENT;
  void GUARD_SATISFIED_NEED_CANNOT_TRIGGER_NEW_BUY;
}
