/**
 * b63-execution-gates — B.6.3 pre-existing bounded payment authority.
 * Evaluation only. Zero execution / authority-creation power.
 */

export const GUARD_AUTONOMY_AUTHORITY_SIGNATURE_VALID =
  "GUARD_AUTONOMY_AUTHORITY_SIGNATURE_VALID" as const;
export const GUARD_B63_CANNOT_CREATE_OR_MUTATE_AUTONOMY_AUTHORITY =
  "GUARD_B63_CANNOT_CREATE_OR_MUTATE_AUTONOMY_AUTHORITY" as const;
export const GUARD_AUTONOMY_AUTHORITY_CAPABILITY_SCOPE =
  "GUARD_AUTONOMY_AUTHORITY_CAPABILITY_SCOPE" as const;
export const GUARD_AUTHORITY_CURRENT_REVOCATION_STATE =
  "GUARD_AUTHORITY_CURRENT_REVOCATION_STATE" as const;
export const GUARD_AUTHORITY_DECISION_BINDS_PAYMENT_APPROVAL_INTENT =
  "GUARD_AUTHORITY_DECISION_BINDS_PAYMENT_APPROVAL_INTENT" as const;

export const AUTHORITY_NOT_PREEXISTING = "AUTHORITY_NOT_PREEXISTING" as const;
export const AUTONOMY_DENIED_INVALID_AUTHORITY_SIGNATURE =
  "AUTONOMY_DENIED_INVALID_AUTHORITY_SIGNATURE" as const;
export const AUTONOMY_DENIED_UNSIGNED_AUTHORITY =
  "AUTONOMY_DENIED_UNSIGNED_AUTHORITY" as const;
export const AUTONOMY_DENIED_NEED_AUTHORITY_CLASS =
  "AUTONOMY_DENIED_NEED_AUTHORITY_CLASS" as const;
export const AUTONOMY_DENIED_CAPABILITY_SCOPE =
  "AUTONOMY_DENIED_CAPABILITY_SCOPE" as const;
export const AUTONOMY_DENIED_SELLER_SCOPE = "AUTONOMY_DENIED_SELLER_SCOPE" as const;
export const AUTONOMY_DENIED_PROVIDER_SCOPE =
  "AUTONOMY_DENIED_PROVIDER_SCOPE" as const;
export const AUTONOMY_DENIED_NETWORK_SCOPE =
  "AUTONOMY_DENIED_NETWORK_SCOPE" as const;
export const AUTONOMY_DENIED_ASSET_SCOPE = "AUTONOMY_DENIED_ASSET_SCOPE" as const;
export const AUTONOMY_DENIED_AUTHORITY_EXPIRED =
  "AUTONOMY_DENIED_AUTHORITY_EXPIRED" as const;
export const AUTONOMY_DENIED_AUTHORITY_NOT_YET_VALID =
  "AUTONOMY_DENIED_AUTHORITY_NOT_YET_VALID" as const;
export const AUTONOMY_DENIED_AUTHORITY_REVOKED =
  "AUTONOMY_DENIED_AUTHORITY_REVOKED" as const;
export const AUTONOMY_DENIED_PER_TRANSACTION_LIMIT =
  "AUTONOMY_DENIED_PER_TRANSACTION_LIMIT" as const;
export const AUTONOMY_DENIED_AGGREGATE_LIMIT =
  "AUTONOMY_DENIED_AGGREGATE_LIMIT" as const;
export const AUTONOMY_DENIED_TRANSACTION_COUNT_LIMIT =
  "AUTONOMY_DENIED_TRANSACTION_COUNT_LIMIT" as const;
export const AUTONOMY_DENIED_WINDOW_SPEND_LIMIT =
  "AUTONOMY_DENIED_WINDOW_SPEND_LIMIT" as const;
export const AUTONOMY_DENIED_WINDOW_TX_COUNT_LIMIT =
  "AUTONOMY_DENIED_WINDOW_TX_COUNT_LIMIT" as const;
export const AUTONOMY_DENIED_SELLER_HISTORY_INSUFFICIENT =
  "AUTONOMY_DENIED_SELLER_HISTORY_INSUFFICIENT" as const;
export const AUTONOMY_DENIED_SELLER_IDENTITY_CHANGE =
  "AUTONOMY_DENIED_SELLER_IDENTITY_CHANGE" as const;
export const AUTONOMY_DENIED_RECENT_AMBIGUOUS_SEND =
  "AUTONOMY_DENIED_RECENT_AMBIGUOUS_SEND" as const;

export const AUTONOMOUS_EXECUTION_REQUIRES_ATOMIC_BUDGET_RESERVATION =
  "AUTONOMOUS_EXECUTION_REQUIRES_ATOMIC_BUDGET_RESERVATION" as const;

export const BLOCKED_B63_VISIBLE_UI_REGRESSION_NO_PAYMENT =
  "BLOCKED_B63_VISIBLE_UI_REGRESSION_NO_PAYMENT" as const;
export const BLOCKED_B63_AUTHORITY_TAMPER = "BLOCKED_B63_AUTHORITY_TAMPER" as const;

export const B63_PREEXISTING_BOUNDED_PAYMENT_AUTHORITY_READY_NO_PAYMENT =
  "B63_PREEXISTING_BOUNDED_PAYMENT_AUTHORITY_READY_NO_PAYMENT" as const;

export const GUARD_B63_CANNOT_SIGN = "GUARD_B63_CANNOT_SIGN" as const;
export const GUARD_B63_CANNOT_SEND = "GUARD_B63_CANNOT_SEND" as const;
export const GUARD_B63_CANNOT_CREATE_PAYMENT_HEADER =
  "GUARD_B63_CANNOT_CREATE_PAYMENT_HEADER" as const;

export type AutonomyOutcome =
  | "AUTONOMY_ALLOWED"
  | "HUMAN_REQUIRED"
  | "AUTONOMY_DENIED"
  | "AUTHORITY_UNAVAILABLE";

export function assertB63HasNoExecutionAuthority(): void {
  void GUARD_B63_CANNOT_SIGN;
  void GUARD_B63_CANNOT_SEND;
  void GUARD_B63_CANNOT_CREATE_PAYMENT_HEADER;
  void GUARD_B63_CANNOT_CREATE_OR_MUTATE_AUTONOMY_AUTHORITY;
}
